apiVersion: v1alpha1
kind: Setting
metadata:
  name: personalassets-settings
spec:
  forms:
    - group: base
      label: 基本设置
      formSchema:
        - $formkit: text
          label: 页面标题
          name: title
          validation: required
          value: "个人资产"
        - $formkit: text
          label: 页面副标题
          name: subtitle
          value: "看得见的家底，理得清的资产。"
        - $formkit: text
          label: 资产 ID 前缀
          name: assetIdPrefix
          value: ""
        - $formkit: number
          label: 资产 ID 长度
          name: assetIdLength
          validation: required|min:2|max:32
          value: 6
        - $formkit: text
          label: 资产列表显示条数
          name: pageSize
          validation: required|Number
          value: 20
